
name: Python Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv grossinger_llm
        source grossinger_llm/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source grossinger_llm/bin/activate
        pytest --cov=app tests/
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
